alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ll="ls -l"
alias n="npm"
alias q="exit"
alias RM="rm -rf --"
alias home="cd ~/"
alias aliases="code ~/.bash_aliases"
alias my-aliases="code /Users/jcardona/www/my_config/.bash_aliases"
# ----------- Run code -----------
alias firebase="/usr/local/lib/node_modules/bin/firebase"
alias ionic="/usr/local/lib/node_modules/bin/ionic"
alias ng="/usr/local/lib/node_modules/bin/ng"
# ----------- Proyectos -----------
alias www="cd /Users/jcardona/www/"
alias rv4="cd /Users/jcardona/www/rebus/v4/"
alias rv4a="cd /Users/jcardona/www/rebus/v4/RebusAdmin/"
alias rv4b="cd /Users/jcardona/www/rebus/v4/RebusBackend/"
alias rv4f="cd /Users/jcardona/www/rebus/v4/RebusFrontend/"
alias rv4o="cd /Users/jcardona/www/rebus/v4/RebusOpinometer/"
alias rv4p="cd /Users/jcardona/www/rebus/v4/RebusPrivate/"
alias rv4s="cd /Users/jcardona/www/rebus/v4/RebusSuperadmin/"
alias rv3c="cd /Users/jcardona/www/rebus/rebusV3Hosting/code/"
alias rv3h="cd /Users/jcardona/www/rebus/rebusV3Hosting/host/"
